name: Pull Request
run-name: ${{ github.event.pull_request.title }} pull request run 🚀
on:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  check-format:
    name: Check Formatting 🔍
    if: ${{ false }}
    uses: ./.github/workflows/check-format.yaml
    permissions:
      contents: read

  build-project:
    name: Build Project 🧱
    if: ${{ false }}
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
    permissions:
      contents: read
